import i18n from "@/locale";
import { PlayArrowFilled } from "@vicons/material";
const { t } = i18n.global;
export default [
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/2",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/3",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/4",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/5",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
	{
		title: t("common.nav.txt1"),
		click() {},
		to: "/6",
		children: [
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
			[
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
				{
					name: t("common.nav.txt1"),
					icon: PlayArrowFilled,
					class: "",
					span: 2,
					style: "",
					click() {},
					to: "",
				},
			],
		],
	},
];
